#config_version=6

mode:
  start_events: start_simon_difficulty_select
  stop_events:
    - villain_selection_complete
    - ball_ended
  priority: 310
  code: mpf.modes.carousel.code.carousel.Carousel

light_player:
  mode_villain_select_started:
    GI:
      color: 000000
    SPOTS:
      color: 000000
      
mode_settings:
  selectable_items:
    - simon_die_hard
    - simon_die_harder
  next_item_events:
    - s_right_flipper_active
  previous_item_events:
    - s_left_flipper_active
  select_item_events:
    - s_fire_active
    - s_actionbtn_active

show_player:
  mode_simon_difficulty_select_started:
    flash_color:
      key: selected_villain_flash
      priority: 120
      loops: -1
      speed: 6
      show_tokens:
        lights: l41, l1000, l1001
        color: ffffff
    InsertsVillainSpinOrange:
      loops: -1
      speed: 50

  set_difficulty_die_hard:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

  set_difficulty_die_harder:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

  mode_simon_difficulty_select_stopped:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

slide_player:
  mode_simon_difficulty_select_started:
    simon_difficulty_select:
      action: play
      expire: 0s
  play_simon_intro:
    simon_intro:
      action: play
      expire: 5s


event_player:
  carousel_item_selected{carousel=="simon_difficulty_select" and item=="simon_die_hard"}:
    - set_difficulty_die_hard
    - play_simon_intro
    - villain_intro_finished|3s
  carousel_item_selected{carousel=="simon_difficulty_select" and item=="simon_die_harder"}:
    - set_difficulty_die_harder
    - play_simon_intro
    - villain_intro_finished|3s
  villain_intro_finished:
    - release_villain_select_vuk
    - start_simon_gruber
    - villain_selection_complete|100ms


variable_player:
  set_difficulty_die_hard:
    selected_diehard_mode:
      string: die_hard
      action: set


  set_difficulty_die_harder:
    selected_diehard_mode:
      string: die_harder
      action: set

  mode_simon_difficulty_select_started:
    villain_difficulty_select_running:
      action: set
      int: 1

  mode_simon_difficulty_select_stopping:
    villain_difficulty_select_running:
      action: set
      int: 0