#config_version=6

mode:
  start_events: ball_started{current_player.central_park_played==0}
  stop_events: ball_ended,multiball_central_park_started
  priority: 200

shot_groups: 
  qualify_central_park:
    shots: central_park_lock_left,central_park_lock_middle,central_park_lock_right
    restart_events: trigger_central_park_ball_locked
    disable_events: multiball_central_park_started
    
    
shots: 
  central_park_lock_left:
    switch: s_TrPF1
    profile: profile_central_park_lock
    show_tokens: 
      lights: l76
  central_park_lock_middle:
    switch: s_TrPF2
    profile: profile_central_park_lock
    show_tokens: 
      lights: l77
  central_park_lock_right:
    switch: s_TrPF3
    profile: profile_central_park_lock
    show_tokens: 
      lights: l78

counters:
  central_park_multiball_counter:
    count_events: qualify_central_park_on_complete
    count_complete_value: 3
    persist_state: true
   
show_player: 
  qualify_central_park_on_complete: 
    nakatomi_ball_locked: 
      key: key_central_park_ball_locked
      loops: 0
      events_when_completed: trigger_central_park_ball_locked
      

slide_player: 
  counter_central_park_multiball_counter_hit{hits==1}:
    centralparkball_1_locked:
      action: play
      expire: 0s 
  counter_central_park_multiball_counter_hit{hits==2}:
    centralparkball_2_locked:
      action: play
      expire: 0s
  counter_central_park_multiball_counter_hit{hits==3}:
    centralpark_mb:
      action: play
      expire: 0s

event_player:
  slide_centralpark_mb_removed:
   - start_central_park_multiball

