#config_version=6
mode:
  start_events:
    - ball_started{current_player.central_park_played==0}
    - multiball_nakatomi_ended{current_player.central_park_played==0}
    - multiball_airplane_ended{current_player.central_park_played==0}
    - mode_ambush_stopped{current_player.central_park_played==0}
    # Hans finished
    - hans_diehard_won_complete{current_player.central_park_played==0}
    - hans_diehard_failed_complete{current_player.central_park_played==0}
    - hans_dieharder_won_complete{current_player.central_park_played==0}
    - hans_dieharder_failed_complete{current_player.central_park_played==0}
    # Katya finished
    - katya_completed{current_player.central_park_played==0}
    - katya_failed{current_player.central_park_played==0}
    - katya_dieharder_completed{current_player.central_park_played==0}
    - katya_dieharder_failed{current_player.central_park_played==0}
    # Karl finished
    - karl_diehard_completed{current_player.central_park_played==0}
    - karl_diehard_failed{current_player.central_park_played==0}
    - karl_dieharder_completed{current_player.central_park_played==0}
    - karl_dieharder_failed{current_player.central_park_played==0}
    # Simon finished
    - simon_completed{current_player.central_park_played==0}
    - simon_failed{current_player.central_park_played==0}
    - simon_dieharder_completed{current_player.central_park_played==0}
    - simon_dieharder_failed{current_player.central_park_played==0}
    # Stuart / Col finished
    - stuart_completed{current_player.central_park_played==0}
    - stuart_failed{current_player.central_park_played==0}
    - stuart_dieharder_completed{current_player.central_park_played==0}
    - stuart_dieharder_failed{current_player.central_park_played==0}
    - col_completed{current_player.central_park_played==0}
    - col_failed{current_player.central_park_played==0}
    - col_dieharder_completed{current_player.central_park_played==0}
    - col_dieharder_failed{current_player.central_park_played==0}
  stop_events:
    - ball_ended
    # Stop during Central Park itself / other multiballs
    - multiball_central_park_started
    - multiball_nakatomi_started
    - multiball_airplane_started
    # Stop during Ambush
    - start_ambush_from_vuk_hold
    - start_ambush_from_mystery
    - mode_ambush_started
    # Hans started
    - start_hans_diehard
    - start_hans_dieharder
    # Katya started
    - start_katya_diehard
    - start_katya_dieharder
    # Karl started
    - start_karl_diehard
    - start_karl_dieharder
    # Simon started
    - start_simon_diehard
    - start_simon_dieharder
    # Stuart / Col started
    - start_stuart_diehard
    - start_stuart_dieharder
    - start_col_diehard
    - start_col_dieharder
    - start_yippee_ki_yay_wizard
    - mode_yippee_ki_yay_wizard_started
  priority: 200
light_player:
  central_park_start_multiball_hit:
    GI:
      color: ffb700
    SPOTS:
      color: 505050
    SPOTS_BUMPER:
      color: 969650
shot_groups:
  qualify_central_park:
    shots: central_park_lock_left,central_park_lock_middle,central_park_lock_right
    restart_events: trigger_central_park_ball_locked
    disable_events:
      - central_park_start_multiball_hit
      - start_central_park_multiball
      - multiball_central_park_started
shots:
  central_park_lock_left:
    switch: s_TrPF1
    profile: profile_central_park_lock
    show_tokens:
      lights: l76
    control_events:
      - events: mystery_award_cp_left_lane
        state: 1
  central_park_lock_middle:
    switch: s_TrPF2
    profile: profile_central_park_lock
    show_tokens:
      lights: l77
    control_events:
      - events: mystery_award_cp_middle_lane
        state: 1
  central_park_lock_right:
    switch: s_TrPF3
    profile: profile_central_park_lock
    show_tokens:
      lights: l78
    control_events:
      - events: mystery_award_cp_right_lane
        state: 1
  central_park_start_multiball:
    profile: cp_start_multiball_profile
    switch: s_upper_pf_entrance
    start_enabled: false
    enable_events: counter_central_park_multiball_counter_hit{hits==3}
    disable_events: central_park_start_multiball_hit
    show_tokens:
      lights: CP_LOCK
      color: 00ff00
counters:
  central_park_multiball_counter:
    count_events: qualify_central_park_on_complete
    count_complete_value: 3
    persist_state: true
    enable_events: mode_qualify_central_park_started
    disable_events:
      - central_park_start_multiball_hit
      - start_central_park_multiball
      - multiball_central_park_started
      - ball_ended
    events_when_complete: trigger_central_park_ball_locked
show_player:
  qualify_central_park_on_complete:
    park_mb_ball_locked:
      key: key_central_park_ball_locked
      loops: 0
      priority: 999
      events_when_completed: trigger_central_park_ball_locked
  central_park_start_multiball_hit:
    park_mb_start:
      key: key_central_park_multiball_start
      loops: 0
      priority: 999
slide_player:
  counter_central_park_multiball_counter_hit{hits==1}:
    centralparkball_1_locked:
      action: play
      expire: 0s
  counter_central_park_multiball_counter_hit{hits==2}:
    centralparkball_2_locked:
      action: play
      expire: 0s
  counter_central_park_multiball_counter_hit{hits==3}:
    centralparkball_3_locked:
      action: play
      expire: 0s
  central_park_start_multiball_hit:
    centralpark_mb:
      action: play
      expire: 0s
event_player:
  slide_centralpark_mb_removed:
    - start_central_park_multiball
variable_player:
  trigger_central_park_ball_locked:
    score:
      action: add
      int: "250000 * current_player.playfield_multiplier"
    eob_bonus_multiball:
      action: add
      int: 100000