#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended, end_skillshot
  priority: 1100

sound_player:
  s_fire_active:
    gunfire:
      action: play
      volume: 1.0

event_player:
  mode_skillshot_started:
    - reset_super_skillshot

  s_plunger_key_active{current_player.super_skillshot_available==0}:
    - s_fire_active

  s_actionbtn_active{current_player.super_skillshot_available==0}:
    - s_fire_active

  s_fire_active:
    - skillshot_check

  skillshot_hit.1{current_player.ball==1}:
    - ball_save_one

  skillshot_hit.1{current_player.ball==2}:
    - ball_save_two

  skillshot_hit.1{current_player.ball==3}:
    - ball_save_three

  s_right_orbit_active{current_player.skillshot_completed==0}:
    - skillshot_miss
    - end_skillshot|2s

  s_right_orbit2_active{current_player.skillshot_completed==0}:
    - skillshot_miss
    - end_skillshot|2s

  s_captiveball_active:
    - super_skillshot_check|250ms

  super_skillshot_check{current_player.skillshot_completed==1 and current_player.super_skillshot_awarded==0}:
    - super_skillshot_award

  super_skillshot_award:
    - villain_start_lit
    - super_skillshot_full_bullets
    - end_skillshot|6s

  skillshot_result_video_finished{current_player.super_skillshot_available==0}:
    - end_skillshot

  timer_super_skillshot_timer_complete:
    - end_skillshot

  ball_will_end:
    - end_skillshot

timers:
  super_skillshot_timer:
    start_value: 3
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - event: skillshot_hit
        action: restart
      - event: skillshot_hit
        action: start
      - event: super_skillshot_award
        action: stop
      - event: mode_skillshot_stopping
        action: stop

show_player:
  mode_skillshot_started:
    flash_action_button_red:
      key: skillshot_action_button_flash
      loops: -1

  s_fire_active:
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      speed: 8
      show_tokens:
        captive: l52

  skillshot_hit:
    flash_action_button_red:
      key: skillshot_action_button_flash
      action: stop
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      speed: 8
      loops: -1
      show_tokens:
        captive: l52

  skillshot_miss:
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      action: stop

  timer_super_skillshot_timer_complete:
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      action: stop

  super_skillshot_award:
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      action: stop
    super_skillshot_plane_bounce:
      key: super_skillshot_plane_bounce
      speed: 1
      loops: 0
    super_skillshot_collected_crazy:
      key: super_skillshot_collected_crazy
      speed: 1
      loops: 2

  mode_skillshot_stopping:
    flash_action_button_red:
      key: skillshot_action_button_flash
      action: stop
    super_skillshot_captive_ready:
      key: super_skillshot_captive_ready
      action: stop
    super_skillshot_plane_bounce:
      key: super_skillshot_plane_bounce
      action: stop
    super_skillshot_collected_crazy:
      key: super_skillshot_collected_crazy
      action: stop

slide_player:
  mode_skillshot_started:
    skillshot:
      action: play
      expire: 0s

  end_skillshot:
    skillshot:
      action: remove
      expire: 0s

  mode_skillshot_stopping:
    skillshot:
      action: remove
      expire: 0s

widget_player:
  super_skillshot_award:
    super_skill_shot:
      action: play
      expire: 6s

  mode_skillshot_stopping:
    super_skill_shot:
      action: remove

variable_player:
  reset_super_skillshot:
    skillshot_completed:
      action: set
      int: 0
    super_skillshot_available:
      action: set
      int: 0
    super_skillshot_awarded:
      action: set
      int: 0

  skillshot_hit:
    skillshot_completed:
      action: set
      int: 1
    super_skillshot_available:
      action: set
      int: 1
    super_skillshot_awarded:
      action: set
      int: 0

  skillshot_miss:
    skillshot_completed:
      action: set
      int: 0
    super_skillshot_available:
      action: set
      int: 0

  timer_super_skillshot_timer_complete:
    skillshot_completed:
      action: set
      int: 0
    super_skillshot_available:
      action: set
      int: 0

  super_skillshot_award:
    score:
      action: add
      int: 1000000
    super_skillshot_awarded:
      action: set
      int: 1
    super_skillshot_available:
      action: set
      int: 0
    bullet_hits:
      action: set
      int: 15

  ball_save_one:
    score:
      action: add
      int: 1000000

  ball_save_two:
    score:
      action: add
      int: 2000000

  ball_save_three:
    score:
      action: add
      int: 4000000