#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 120

ball_holds: 
  nakatomi_lock_wait:
    enable_events: qualify_nakatomi_on_complete
    disable_events: slide_ball_1_locked_removed.1
    hold_devices: tower_vuk
    balls_to_hold: 1
    release_all_events: tilt, slide_ball_1_locked_removed.2

event_player: 
  timer_nakatomi_lock_reset_complete: 
    - nakatomi_lock_open
  qualify_nakatomi_on_complete: 
    - nakatomi_lock_open


shot_groups: 
  qualify_nakatomi:
    shots: nakatomi_lock_left,nakatomi_lock_right

shots: 
  nakatomi_lock_left:
    switch: s_holly_l
    profile: profile_nakatomi_lock
    show_tokens: 
      lights: l17
  nakatomi_lock_right:
    switch: s_holly_l1
    profile: profile_nakatomi_lock
    show_tokens: 
      lights: l16
  nakatomi_lock_lit:
    profile: profile_off_then_flash
    show_tokens: 
      lights: l7
      color: 00ff00
    control_events: 
      - events: qualify_nakatomi_on_complete
        state: 1

show_player: 
  ball_hold_nakatomi_lock_wait_full: 
    nakatomi_ball_locked: 
      key: key_nakatomi_ball_locked
      loops: 0


slide_player: 
  qualify_nakatomi_on_complete: 
    lock_is_lit:
      action: play
      expire: 0s
  ball_hold_nakatomi_lock_wait_full: 
    ball_1_locked:
      action: play
      expire: 0s


timers: 
  nakatomi_lock_reset:
    start_value: 0
    end_value: 1
    direction: up
    control_events: 
      - event: qualify_nakatomi_on_complete
        action: restart
    restart_on_complete: True
    start_running: False
    tick_interval: 60000ms


