#config_version=6

mode:
  start_events: ball_started{current_player.played_naktomi_multiball == 0}
  stop_events: ball_ended, multiball_nakatomi_started
  priority: 120

event_player: 
  timer_nakatomi_lock_reset_complete:
    - nakatomi_lock_open
  qualify_nakatomi_on_complete:
    - nakatomi_lock_open
    - nakatomi_entrance_lock_open
  qualify_nakatomi_on_complete{current_player.nakatomi_balls_locked < 3}:
    - enable_nakatomi_multiball_lock
  trigger_nakatomi_ball_locked:
    - nakatomi_entrance_lock_close
  mode_qualify_nakatomi_started{current_player.shot_nakatomi_lock_lit == 1}:
    - nakatomi_entrance_lock_open
  mode_qualify_nakatomi_started{current_player.shot_nakatomi_lock_lit == 0}:
    - nakatomi_entrance_lock_close
  mode_qualify_nakatomi_started{current_player.shot_nakatomi_lock_lit == 1 and current_player.nakatomi_balls_locked < 3}:
    - enable_nakatomi_multiball_lock
  mode_qualify_nakatomi_started{current_player.nakatomi_balls_locked > 0}:
    - nakatomi_lock_open
  multiball_nakatomi_started.1:
    - nakatomi_lock_close
    - nakatomi_entrance_lock_close


multiball_locks: 
  nakatomi:
    balls_to_lock: 3
    lock_devices: tower_vuk
    balls_to_replace: 2
    enable_events: enable_nakatomi_multiball_lock
    disable_events: trigger_nakatomi_ball_locked
    reset_count_for_current_player_events: restart_nakatomi_locks
    locked_ball_counting_strategy: physical_only

multiballs: 
  multiball_nakatomi:
    start_events: slide_nakatomi_mb_removed
    ball_count: 3
    ball_count_type: total
    shoot_again: 20000
    hurry_up: 3000
    grace_period: 2000
    ball_locks: tower_nakatomi

queue_relay_player: 
  balldevice_trough_ball_eject_attempt{current_player.ball_locking_nakatomi == 1}: 
    post: wait_for_naktomi_locking_slide
    wait_for: trigger_nakatomi_ball_locked


shot_groups: 
  qualify_nakatomi:
    shots: nakatomi_lock_left,nakatomi_lock_right
    restart_events: trigger_nakatomi_ball_locked

shots: 
  nakatomi_lock_left:
    switch: s_holly_l
    profile: profile_nakatomi_lock
    show_tokens: 
      lights: l17
  nakatomi_lock_right:
    switch: s_holly_l1
    profile: profile_nakatomi_lock
    show_tokens: 
      lights: l16
  nakatomi_lock_lit:
    profile: profile_off_then_flash
    show_tokens: 
      lights: l7
      color: 00ff00
    control_events: 
      - events: qualify_nakatomi_on_complete
        state: 1
      - events: trigger_nakatomi_ball_locked
        state: 0

show_player: 
  multiball_lock_nakatomi_locked_ball: 
    nakatomi_ball_locked: 
      key: key_nakatomi_ball_locked
      loops: 0
      events_when_completed: trigger_nakatomi_ball_locked


slide_player: 
  qualify_nakatomi_on_complete: 
    lock_is_lit:
      action: play
      expire: 0s
  multiball_lock_nakatomi_locked_ball{current_player.nakatomi_balls_locked == 0}: 
    ball_1_locked:
      action: play
      expire: 0s
  multiball_lock_nakatomi_locked_ball{current_player.nakatomi_balls_locked == 1}: 
    ball_2_locked:
      action: play
      expire: 0s
  multiball_lock_nakatomi_locked_ball{current_player.nakatomi_balls_locked == 2}: 
    nakatomi_mb:
      action: play
      expire: 0s


timers: 
  nakatomi_lock_reset:
    start_value: 0
    end_value: 1
    direction: up
    control_events: 
      - event: qualify_nakatomi_on_complete
        action: restart
      - event: mode_qualify_nakatomi_started{current_player.nakatomi_balls_locked > 0}
        action: restart
      - event: multiball_nakatomi_started
        action: stop
    restart_on_complete: True
    start_running: False
    tick_interval: 60000ms

variable_player: 
  mode_qualify_nakatomi_started: 
    ball_locking_nakatomi: 
      action: set
      int: 0

  multiball_lock_nakatomi_locked_ball: 
    ball_locking_nakatomi: 
      action: set
      int: 1

  trigger_nakatomi_ball_locked.10: 
    ball_locking_nakatomi: 
      action: set
      int: 0
    nakatomi_balls_locked: 
      action: add
      int: 1

coil_player: 
  trigger_nakatomi_ball_locked: c_towervuk_eject

