#config_version=6

mode:
  start_events: start_hans_difficulty_select
  stop_events:
    - villain_selection_complete
    - ball_ended
  priority: 310
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items:
    - hans_die_hard
    - hans_die_harder

  next_item_events:
    - s_right_flipper_active

  previous_item_events:
    - s_left_flipper_active

  select_item_events:
    - s_fire_active
    - s_actionbtn_active

show_player:
  mode_hans_difficulty_select_started:
    flash_color:
      key: selected_villain_flash
      priority: 120
      loops: -1
      speed: 6
      show_tokens:
        lights: l43, l1000, l1001
        color: 00ff00
    InsertsVillainSpinOrange:
      loops: -1
      speed: 50

  set_difficulty_die_hard:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

  set_difficulty_die_harder:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

  mode_hans_difficulty_select_stopped:
    selected_villain_flash:
      action: stop
    InsertsVillainSpinOrange:
      action: stop

slide_player:
  mode_hans_difficulty_select_started:
    hans_difficulty_select:
      action: play
      expire: 0s

  play_hans_intro:
    hans_intro:
      action: play
      expire: 5s

  hide_hans_difficulty_select:
    hans_difficulty_select:
      action: remove

event_player:
  carousel_item_selected{carousel=="hans_difficulty_select" and item=="hans_die_hard" and current_player.hans_complete!=1}:
    - set_difficulty_die_hard
    - hide_hans_difficulty_select
    - play_hans_intro
    - hans_mode_start_warning|2.5s
    - start_hans_diehard|3s
    - villain_intro_finished|3.1s

  carousel_item_selected{carousel=="hans_difficulty_select" and item=="hans_die_harder" and current_player.hans_complete!=1}:
    - set_difficulty_die_harder
    - hide_hans_difficulty_select
    - play_hans_intro
    - hans_mode_start_warning|2.5s
    - start_hans_dieharder|3s
    - villain_intro_finished|3.1s


  villain_intro_finished:
    - release_villain_select_vuk
    - villain_selection_complete|100ms

variable_player:
  set_difficulty_die_hard:
    selected_diehard_mode:
      string: die_hard
      action: set

  set_difficulty_die_harder:
    selected_diehard_mode:
      string: die_harder
      action: set

  mode_hans_difficulty_select_started:
    villain_difficulty_select_running:
      action: set
      int: 1

  mode_hans_difficulty_select_stopping:
    villain_difficulty_select_running:
      action: set
      int: 0

light_player:
  hans_mode_start_warning:
    f142:
      color: 00ff00
      fade: 100ms

  start_hans_diehard:
    f142: off

  start_hans_dieharder:
    f142: off

    GI:
      color: 000000
    SPOTS:
      color: 000000