#config_version=6

mode:
  start_events: game_ended, reset_complete
  stop_events: game_start, service_mode_entered
  priority: 10

event_player: 
  mode_attract_started: 
    - play_show_xmas
    - play_show_start_button_flash


light_player: 
  mode_attract_started: 
    GI: 
      color: 000000


show_player: 
  play_show_xmas: 
    attract_christmas: 
      key: key_attract_christmas
  play_show_start_button_flash: 
    flash_start_button: 
      key: key_attract_start_button_flash


slide_player: 
  mode_attract_started: 
    attract:
      action: play
      expire: 0s



