#config_version=6

mode:
  start_events:
    - start_katya_diehard{current_player.katya_complete!=1}
  stop_events:
    - katya_completed
    - katya_failed
  priority: 250

timers:
  katya_timer:
    start_value: 93
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true
    control_events:
      - event: katya_completed
        action: stop
      - event: katya_failed
        action: stop

ball_saves:
  katya_diehard_complete_save:
    active_time: 8s
    hurry_up_time: 3s
    grace_period: 5s
    auto_launch: true
    balls_to_save: 1
    enable_events:
      - katya_victory_sequence


counters:
  katya_loop_counter:
    count_events:
      - katya_left_loop_hit
      - katya_right_loop_hit
      - katya_upper_loop_hit
    starting_count: 0
    count_complete_value: 5
    direction: up
    persist_state: false
    reset_on_complete: false
    events_when_complete:
      - katya_loops_complete
    reset_events:
      - mode_katya_diehard_started

shots:
  katya_left_loop:
    hit_events: left_orbit_hit
    enable_events:
      - mode_katya_diehard_started
      - katya_left_loop_relight
    disable_events:
      - katya_left_loop_hit
      - katya_loops_complete
      - katya_completed
      - katya_failed

  katya_right_loop:
    hit_events: right_orbit_hit
    enable_events:
      - mode_katya_diehard_started
      - katya_right_loop_relight
    disable_events:
      - katya_right_loop_hit
      - katya_loops_complete
      - katya_completed
      - katya_failed

  katya_upper_loop:
    switch: s_mid_orbit
    enable_events:
      - mode_katya_diehard_started
      - katya_upper_loop_relight
    disable_events:
      - katya_upper_loop_hit
      - katya_loops_complete
      - katya_completed
      - katya_failed

  katya_captive_final:
    switch: s_captiveball
    enable_events:
      - katya_loops_complete
    disable_events:
      - katya_completed
      - katya_failed

event_player:
  mode_katya_diehard_started:
    - villain_mode_started
    - katya_start
    - katya_diehard_music_start
    - reset_bullet_total
    - reset_bullets
    - nakatomi_entrance_lock_close
    - wire_ramp_exit_open

  mode_katya_diehard_stopping:
    - villain_mode_stopped

  timer_katya_timer_complete:
    - katya_escape_sequence

  ball_ended{current_player.katya_diehard_completion_active==0}:
    - katya_escape_sequence

  ball_ended{current_player.katya_diehard_completion_active==1}:
    - reset_bullet_total
    - reset_bullets

  ball_drain{current_player.katya_diehard_completion_active==0}:
    - katya_ball_drain_escape

  ball_drain{current_player.katya_diehard_completion_active==1}:
    - reset_bullet_total
    - reset_bullets

  katya_ball_drain_escape:
    - katya_failed|4s

  katya_escape_sequence:
    - katya_failed_delay

  katya_failed_delay:
    - katya_failed|4s

  katya_failed:
    - reset_bullet_total
    - reset_bullets
    - wire_ramp_exit_close

  katya_completed:
    - reset_bullet_total
    - reset_bullets
    - count_katya_for_extra_ball
    - wire_ramp_exit_close
    
  katya_left_loop_hit{device.counters.katya_loop_counter.value<5}:
    - katya_loop_hit_scored
    - katya_left_loop_relight|3s

  katya_right_loop_hit{device.counters.katya_loop_counter.value<5}:
    - katya_loop_hit_scored
    - katya_right_loop_relight|3s

  katya_upper_loop_hit{device.counters.katya_loop_counter.value<5}:
    - katya_loop_hit_scored
    - katya_upper_loop_relight|3s

  katya_captive_final_hit:
    - katya_victory_sequence

  katya_victory_sequence:
    - katya_completed_show
    - katya_completed|4s

variable_player:
  katya_start:
    villain_mode_running:
      int: 1
      action: set

    katya_diehard_completion_active:
      int: 0
      action: set

    katya_shots:
      int: 0
      action: set

    katya_diehard_remaining:
      int: 93
      action: set

    villain_bonus:
      int: 500000
      action: add

  timer_katya_timer_tick:
    katya_diehard_remaining:
      int: ticks
      action: set

  katya_loop_hit_scored:
    score:
      action: add
      int: "1500000 * current_player.playfield_multiplier"

    villain_bonus:
      action: add
      int: 1500000

    katya_shots:
      action: add
      int: 1

  katya_victory_sequence:
    katya_completion_active:
      int: 1
      action: set

    eob_bonus_villains:
      int: 1000000
      action: add

  katya_captive_final_hit:
    score:
      action: add
      int: "3000000 * current_player.playfield_multiplier"

    villain_bonus:
      action: add
      int: 3000000

  katya_completed:
    katya_complete:
      int: 1
      action: set

    modes_complete:
      action: add
      int: 1

  mode_katya_diehard_stopping:
    villain_mode_running:
      int: 0
      action: set

    katya_diehard_completion_active:
      int: 0
      action: set

    villains_completed:
      action: add
      int: 1

light_player:
  mode_katya_diehard_started:
    GI:
      color: ff00ff
    SPOTS:
      color: 505050
    SPOTS_BUMPER:
      color: 700070
    l1000:
      color: ff00ff
    l1001:
      color: ff00ff

  katya_completed:
    l1000: off
    l1001: off
    l42:
      color: ff00ff

  katya_failed:
    l1000: off
    l1001: off

shows:
  katya_left_loop_flash:
    - duration: 200ms
      lights:
        l20: ff00ff
    - duration: 200ms
      lights:
        l20: off

  katya_right_loop_flash:
    - duration: 200ms
      lights:
        l22: ff00ff
    - duration: 200ms
      lights:
        l22: off

  katya_upper_loop_flash:
    - duration: 200ms
      lights:
        l23: ff00ff
    - duration: 200ms
      lights:
        l23: off

  katya_captive_flash:
    - duration: 120ms
      lights:
        l52: ff0000
    - duration: 120ms
      lights:
        l52: off

  katya_hit_flashers:
    - duration: 80ms
      lights:
        f142: ff0000
        f143: ff0000
        f144: ff0000
        f145: ff0000
        f146: ff0000
        f147: ff0000
    - duration: 80ms
      lights:
        f142: off
        f143: off
        f144: off
        f145: off
        f146: off
        f147: off

  katya_insert_flash:
    - duration: 200ms
      lights:
        l42: ff00ff
    - duration: 200ms
      lights:
        l42: off

show_player:
  ball_save_katya_diehard_complete_save_enabled:
    flash_color_with_fade:
      key: katya_diehard_ball_save_flash
      loops: -1
      speed: 2
      show_tokens:
        lights: BALL_SAVE
        color: ff00ff
        fade: 500

  ball_save_katya_diehard_complete_save_hurry_up:
    flash_color:
      key: katya_diehard_ball_save_flash
      loops: -1
      speed: 7
      show_tokens:
        lights: BALL_SAVE
        color: ff00ff

  ball_save_katya_diehard_complete_save_disabled:
    flash_color_with_fade:
      action: stop
      key: katya_diehard_ball_save_flash
    flash_color:
      action: stop
      key: katya_diehard_ball_save_flash

  mode_katya_diehard_started:
    katya_left_loop_flash:
      loops: -1
    katya_right_loop_flash:
      loops: -1
    katya_upper_loop_flash:
      loops: -1
    katya_insert_flash:
      loops: -1

  katya_loop_hit_scored:
    katya_hit_flashers:
      loops: 2

  katya_left_loop_hit:
    katya_left_loop_flash:
      action: stop

  katya_left_loop_relight:
    katya_left_loop_flash:
      loops: -1

  katya_right_loop_hit:
    katya_right_loop_flash:
      action: stop

  katya_right_loop_relight:
    katya_right_loop_flash:
      loops: -1

  katya_upper_loop_hit:
    katya_upper_loop_flash:
      action: stop

  katya_upper_loop_relight:
    katya_upper_loop_flash:
      loops: -1

  katya_loops_complete:
    katya_left_loop_flash:
      action: stop
    katya_right_loop_flash:
      action: stop
    katya_upper_loop_flash:
      action: stop
    katya_captive_flash:
      loops: -1

  katya_completed:
    katya_diehard_ball_save_flash:
      action: stop
    katya_captive_flash:
      action: stop
    katya_insert_flash:
      action: stop

  katya_failed:
    katya_diehard_ball_save_flash:
      action: stop
    katya_left_loop_flash:
      action: stop
    katya_right_loop_flash:
      action: stop
    katya_upper_loop_flash:
      action: stop
    katya_captive_flash:
      action: stop
    katya_insert_flash:
      action: stop

  mode_katya_diehard_stopping:
    katya_diehard_ball_save_flash:
      action: stop
    katya_left_loop_flash:
      action: stop
    katya_right_loop_flash:
      action: stop
    katya_upper_loop_flash:
      action: stop
    katya_captive_flash:
      action: stop
    katya_insert_flash:
      action: stop

slide_player:
  mode_katya_diehard_started:
    katya_diehard_background:
      action: play
      expire: 0s
      priority: 500

  mode_katya_diehard_stopping:
    katya_diehard_background:
      action: remove

  katya_loop_hit_scored{current_player.katya_shots==1}:
    katya_hit_1:
      action: play
      expire: 4s
      priority: 600

  katya_loop_hit_scored{current_player.katya_shots==2}:
    katya_hit_2:
      action: play
      expire: 4s
      priority: 600

  katya_loop_hit_scored{current_player.katya_shots==3}:
    katya_hit_3:
      action: play
      expire: 4s
      priority: 600

  katya_loop_hit_scored{current_player.katya_shots==4}:
    katya_hit_4:
      action: play
      expire: 4s
      priority: 600

  katya_loop_hit_scored{current_player.katya_shots==5}:
    katya_hit_5:
      action: play
      expire: 4s
      priority: 600

  katya_completed_show:
    katya_diehard_background:
      action: remove

    katya_defeated:
      action: play
      expire: 4s
      priority: 10000

  katya_ball_drain_escape:
    katya_diehard_background:
      action: remove

    katya_escaped:
      action: play
      expire: 4s
      priority: 10000

  katya_failed:
    katya_diehard_background:
      action: remove

    katya_escaped:
      action: play
      expire: 4s
      priority: 10000

widget_player:
  mode_katya_diehard_started:
    katya_timer_widget:
      slide: katya_diehard_background
      action: play
    katya_diehard_progress_widget:
      slide: katya_diehard_background
      action: play

  mode_katya_diehard_stopping:
    katya_timer_widget:
      action: remove
    katya_diehard_progress_widget:
      action: remove

  katya_completed:
    katya_timer_widget:
      action: remove
    katya_diehard_progress_widget:
      action: remove

  katya_failed:
    katya_timer_widget:
      action: remove
    katya_diehard_progress_widget:
      action: remove

sound_player:
  katya_diehard_music_start:
    katyatheme:
      key: main_music
      action: play
      loops: -1
      volume: 0.7

  mode_katya_diehard_stopping:
    katyatheme:
      key: main_music
      action: stop