#config_version=6

mode:
  code: mpf.modes.high_score.code.high_score.HighScore
  start_events: game_ending, start_high_score
  stop_events: high_score_complete
  priority: 1500
  game_mode: False
  use_wait_queue: true

event_player: 
  s_left_flipper_active: 
    text_input: {action: "left"}
  s_right_flipper_active: 
    text_input: {action: "right"}
  s_start_active: 
    text_input: {action: "select"}
  s_fire_active: 
    text_input: {action: "select"}
  s_plunger_key_active: 
    text_input: {action: "select"}


high_score:
  _overwrite: true
  categories: 
    score:
      - YIPPIE KI YAY CHAMPION
      - DETECTIVE LIEUTENANT
      - BEAT COP
      - PART TIME SECURITY GUARD
  defaults:
    score:
      - BW: 120000000
      - EJS: 9000000
      - LFS: 5000000
      - DIE: 10
  enter_initials_timeout: 90000ms
  award_slide_display_time: 0ms

slide_player: 
  high_score_enter_initials: 
    high_score:
      action: play
      expire: 0s



