#config_version=6

mode:
  start_events:
    - start_katya_dieharder{current_player.katya_complete==0}
  stop_events:
    - katya_dieharder_completed
    - katya_dieharder_failed
  priority: 170

timers:
  katya_dieharder_timer:
    start_value: 93
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - event: katya_dieharder_start_normal_timer
        action: restart
        value: 93

      - event: katya_dieharder_start_bonus_timer
        action: restart
        value: 123

      - event: katya_dieharder_completed
        action: stop

      - event: katya_dieharder_failed
        action: stop

ball_saves:
  katya_dieharder_complete_save:
    active_time: 8s
    hurry_up_time: 3s
    grace_period: 5s
    auto_launch: true
    balls_to_save: 1
    enable_events:
      - katya_dieharder_victory_sequence

counters:
  katya_dieharder_loop_counter:
    count_events:
      - katya_dieharder_left_loop_hit
      - katya_dieharder_right_loop_hit
      - katya_dieharder_upper_loop_hit
    starting_count: 0
    count_complete_value: 5
    direction: up
    persist_state: false
    reset_on_complete: false
    reset_events:
      - mode_katya_dieharder_started
    events_when_complete:
      - katya_dieharder_loops_complete

shots:
  katya_dieharder_left_loop:
    hit_events: left_orbit_hit
    enable_events:
      - mode_katya_dieharder_started
      - katya_dieharder_left_loop_relight
    disable_events:
      - katya_dieharder_left_loop_hit
      - katya_dieharder_loops_complete
      - katya_dieharder_completed
      - katya_dieharder_failed
      - katya_dieharder_fail_mode

  katya_dieharder_right_loop:
    hit_events: right_orbit_hit
    enable_events:
      - mode_katya_dieharder_started
      - katya_dieharder_right_loop_relight
    disable_events:
      - katya_dieharder_right_loop_hit
      - katya_dieharder_loops_complete
      - katya_dieharder_completed
      - katya_dieharder_failed
      - katya_dieharder_fail_mode

  katya_dieharder_upper_loop:
    switch: s_mid_orbit
    enable_events:
      - mode_katya_dieharder_started
      - katya_dieharder_upper_loop_relight
    disable_events:
      - katya_dieharder_upper_loop_hit
      - katya_dieharder_loops_complete
      - katya_dieharder_completed
      - katya_dieharder_failed
      - katya_dieharder_fail_mode

  katya_dieharder_captive_final:
    switch: s_captiveball
    enable_events:
      - katya_dieharder_loops_complete
    disable_events:
      - katya_dieharder_completed
      - katya_dieharder_failed
      - katya_dieharder_fail_mode

event_player:
  mode_katya_dieharder_started:
    - villain_mode_started
    - katya_dieharder_start
    - katya_dieharder_music_start
    - reset_bullet_total
    - reset_bullets
    - nakatomi_entrance_lock_close
    - wire_ramp_exit_open

  mode_katya_dieharder_started{current_player.hans_bonus==1}:
    - katya_dieharder_start_bonus_timer
    - clear_hans_bonus

  mode_katya_dieharder_started{current_player.hans_bonus!=1}:
    - katya_dieharder_start_normal_timer

  mode_katya_dieharder_stopping:
    - villain_mode_stopped
    - enable_katya_dieharder_flippers

  timer_katya_dieharder_timer_complete:
    - katya_dieharder_fail_mode

  ball_drain{current_player.katya_dieharder_completion_active==0 and current_player.katya_dieharder_failed_active==0}:
    - katya_dieharder_ball_drain_escape

  ball_drain{current_player.katya_dieharder_completion_active==1}:
    - reset_bullet_total
    - reset_bullets

  ball_drain{current_player.katya_dieharder_failed_active==1}:
    - katya_dieharder_failed|4s

  ball_ended{current_player.katya_dieharder_completion_active==0 and current_player.katya_dieharder_failed_active==0}:
    - katya_dieharder_escape_sequence

  ball_ended{current_player.katya_dieharder_completion_active==1}:
    - reset_bullet_total
    - reset_bullets

  ball_ended{current_player.katya_dieharder_failed_active==1}:
    - katya_dieharder_failed|4s

  katya_dieharder_ball_drain_escape:
    - katya_dieharder_failed|4s

  katya_dieharder_escape_sequence:
    - katya_dieharder_failed_delay

  katya_dieharder_failed_delay:
    - katya_dieharder_failed|4s

  katya_dieharder_failed:
    - reset_bullet_total
    - reset_bullets

  katya_dieharder_completed:
    - reset_bullet_total
    - reset_bullets

  katya_dieharder_left_loop_hit{device.counters.katya_dieharder_loop_counter.value<5}:
    - katya_dieharder_loop_hit_scored
    - katya_dieharder_left_loop_relight|3s

  katya_dieharder_right_loop_hit{device.counters.katya_dieharder_loop_counter.value<5}:
    - katya_dieharder_loop_hit_scored
    - katya_dieharder_right_loop_relight|3s

  katya_dieharder_upper_loop_hit{device.counters.katya_dieharder_loop_counter.value<5}:
    - katya_dieharder_loop_hit_scored
    - katya_dieharder_upper_loop_relight|3s

  katya_dieharder_captive_final_hit:
    - katya_dieharder_victory_sequence

  katya_dieharder_victory_sequence:
    - katya_dieharder_completed_show
    - katya_dieharder_completed|4s


light_player:
  mode_katya_dieharder_started:
    GI:
      color: ff00ff

    SPOTS:
      color: 400040

    SPOTS_BUMPER:
      color: 700070

    l1000:
      color: ff00ff

    l1001:
      color: ff00ff

  katya_dieharder_completed:
    l1000: off
    l1001: off

    l42:
      color: ff00ff

  katya_dieharder_failed:
    l1000: off
    l1001: off

  katya_dieharder_fail_mode:
    GI: off
    SPOTS: off
    SPOTS_BUMPER: off
    INSERT: off
    LeftSling: off
    RightSling: off

    l1000: off
    l1001: off

variable_player:
  katya_dieharder_start:
    villain_mode_running:
      int: 1
      action: set

    katya_dieharder_failed_active:
      int: 0
      action: set

    katya_dieharder_completion_active:
      int: 0
      action: set

    katya_dieharder_shots:
      int: 0
      action: set

    katya_dieharder_time:
      int: 93
      action: set

    villain_bonus:
      int: 500000
      action: add

  clear_hans_bonus:
    hans_bonus:
      int: 0
      action: set

  timer_katya_dieharder_timer_tick:
    katya_dieharder_remaining:
      int: ticks
      action: set

  katya_dieharder_loop_hit_scored:
    score:
      int: "1500000 * current_player.playfield_multiplier"
      action: add

    villain_bonus:
      int: 1500000
      action: add

    katya_dieharder_shots:
      int: 1
      action: add

  katya_dieharder_victory_sequence:
    katya_dieharder_completion_active:
      int: 1
      action: set

    eob_bonus_villains:
      int: 1000000
      action: add

    score:
      int: current_player.score
      action: add

  katya_dieharder_fail_mode:
    katya_dieharder_failed_active:
      int: 1
      action: set

  katya_dieharder_captive_final_hit:
    score:
      int: "3000000 * current_player.playfield_multiplier"
      action: add

    villain_bonus:
      int: 3000000
      action: add

  katya_dieharder_completed:
    katya_complete:
      int: 1
      action: set

    katya_dieharder_complete:
      int: 1
      action: set

    katya_bonus:
      int: 1
      action: set

    modes_complete:
      int: 1
      action: add

  mode_katya_dieharder_stopping:
    villain_mode_running:
      int: 0
      action: set

    katya_dieharder_failed_active:
      int: 0
      action: set

    katya_dieharder_completion_active:
      int: 0
      action: set