#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 115

ball_holds:
  mystery_hold:
    enable_events: mystery_open_vault
    disable_events: mystery_awarded
    hold_devices: kickervault1_eject
    balls_to_hold: 1
    release_all_events:
      - tilt
      - mystery_awarded

shot_groups:
  mystery_ho:
    shots:
      - vault_h
      - vault_o
    restart_events:
      - mystery_ho_qualified_step
      - mystery_awarded

shots:
  vault_h:
    switch: s_holly_h
    profile: profile_mystery_ho
    start_enabled: true
    show_tokens:
      lights: l30
      color: 00ff00

  vault_o:
    switch: s_holly_o
    profile: profile_mystery_ho
    start_enabled: true
    show_tokens:
      lights: l31
      color: 00ff00

  vault_mystery:
    profile: profile_mystery
    show_tokens:
      lights: l60
      color: 00ff00
    control_events:
      - events: mystery_close_vault
        state: 0
      - events: mystery_open_vault
        state: 1

event_player:
  mode_mystery_started:
    - mystery_close_vault

  mystery_ho_on_complete{current_player.mystery_hits_count < 2}:
    - mystery_ho_qualified_step

  mystery_ho_on_complete{current_player.mystery_hits_count >= 2}:
    - mystery_open_vault

  ball_hold_mystery_hold_full:
    - mystery_close_vault
    - mystery_scroll_start

  timer_mystery_scroll_complete:
    - mystery_pick_award

  # Add-A-Ball first if a multiball is active
  mystery_pick_award{current_player.mystery_multiball_active == 1}:
    - mystery_award_add_a_ball

  mystery_pick_award{current_player.mystery_multiball_active == 0}:
    - mystery_pick_normal_award

  # These events track your main multiballs
  multiball_nakatomi_started:
    - mystery_multiball_active
  multiball_airplane_started:
    - mystery_multiball_active
  multiball_central_park_started:
    - mystery_multiball_active

  multiball_nakatomi_ended:
    - mystery_multiball_inactive
  multiball_airplane_ended:
    - mystery_multiball_inactive
  multiball_central_park_ended:
    - mystery_multiball_inactive

  mystery_award_add_a_ball:
    - add_a_ball_in_multiball
    - mystery_awarded

  mystery_award_points:
    - mystery_awarded
  mystery_award_tower_lock:
    - mystery_awarded
  mystery_award_airplane_lock:
    - mystery_awarded
  mystery_award_park_lock:
    - mystery_awarded
  mystery_award_villain:
    - mystery_awarded
  mystery_award_ball_save:
    - mystery_awarded
  mystery_award_bonus_x:
    - mystery_awarded
  mystery_award_hold_bonus_x:
    - mystery_awarded
  mystery_award_super_spinner:
    - mystery_awarded
  mystery_award_super_jets:
    - mystery_awarded
  mystery_award_playfield_x:
    - mystery_awarded
  mystery_award_ambush:
    - mystery_awarded
  mystery_award_extra_ball_lit:
    - mystery_awarded

  mystery_awarded:
    - mystery_close_vault
    - mystery_reset_ho

random_event_player:
  mystery_pick_normal_award:
    events:
      mystery_award_points: 20
      mystery_award_tower_lock: 8
      mystery_award_airplane_lock: 8
      mystery_award_park_lock: 8
      mystery_award_villain: 8
      mystery_award_ball_save: 8
      mystery_award_bonus_x: 8
      mystery_award_hold_bonus_x: 8
      mystery_award_super_spinner: 8
      mystery_award_super_jets: 8
      mystery_award_playfield_x: 8
      mystery_award_ambush: 8
      mystery_award_extra_ball_lit: 4
    scope: player
    force_all: false

timers:
  mystery_scroll:
    start_value: 0
    end_value: 7
    direction: up
    tick_interval: 500ms
    start_running: false
    restart_on_complete: false
    control_events:
      - event: mystery_scroll_start
        action: restart

show_player:
  mystery_open_vault:
    flicker_color:
      key: key_mystery_open_vault
      speed: 4
      show_tokens:
        lights: l84
        color: FFFFFF

  mystery_close_vault:
    flicker_color:
      action: stop
      key: key_mystery_open_vault

  mystery_awarded:
    flicker_color:
      key: key_mystery_awarded
      loops: 2
      speed: 4
      show_tokens:
        lights: f147
        color: 00ff00

slide_player:
  ball_hold_mystery_hold_full:
    mystery:
      action: play
      expire: 7s

widget_player:
  mystery_ho_qualified_step:
    mystery_qualify:
      action: play
      expire: 3s

  mystery_award_add_a_ball:
    mystery_award_add_a_ball:
      action: play
      expire: 3s

  mystery_award_points:
    mystery_award_points:
      action: play
      expire: 3s

  mystery_award_tower_lock:
    mystery_award_tower_lock:
      action: play
      expire: 3s

  mystery_award_airplane_lock:
    mystery_award_airplane_lock:
      action: play
      expire: 3s

  mystery_award_park_lock:
    mystery_award_park_lock:
      action: play
      expire: 3s

  mystery_award_villain:
    mystery_award_villain:
      action: play
      expire: 3s

  mystery_award_ball_save:
    mystery_award_ball_save:
      action: play
      expire: 3s

  mystery_award_bonus_x:
    mystery_award_bonus_x:
      action: play
      expire: 3s

  mystery_award_hold_bonus_x:
    mystery_award_hold_bonus_x:
      action: play
      expire: 3s

  mystery_award_super_spinner:
    mystery_award_super_spinner:
      action: play
      expire: 3s

  mystery_award_super_jets:
    mystery_award_super_jets:
      action: play
      expire: 3s

  mystery_award_playfield_x:
    mystery_award_playfield_x:
      action: play
      expire: 3s

  mystery_award_ambush:
    mystery_award_ambush:
      action: play
      expire: 3s

  mystery_award_extra_ball_lit:
    mystery_award_extra_ball_lit:
      action: play
      expire: 3s

variable_player:
  mystery_ho_qualified_step:
    mystery_hits_count:
      action: add
      int: 1

  mystery_reset_ho:
    mystery_hits_count:
      action: set
      int: 0

  mystery_multiball_active:
    mystery_multiball_active:
      action: set
      int: 1

  mystery_multiball_inactive:
    mystery_multiball_active:
      action: set
      int: 0

  mystery_award_points:
    score: 2500000
    mystery_awarded_index:
      action: set
      int: 11

  mystery_award_tower_lock:
    tower_lock_lit:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 0

  mystery_award_airplane_lock:
    airplane_lock_lit:
      action: set
      int: 1
    airplane_captive_hits:
      action: set
      int: 0
    mystery_awarded_index:
      action: set
      int: 1

  mystery_award_park_lock:
    park_locks:
      action: add
      int: 1
    mystery_awarded_index:
      action: set
      int: 2

  mystery_award_villain:
    collected_bullets:
      action: set
      int: 15
    mystery_awarded_index:
      action: set
      int: 3

  mystery_award_ball_save:
    mystery_ball_save_awarded:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 4

  mystery_award_bonus_x:
    bonus_multiplier:
      action: add
      int: 1
    mystery_awarded_index:
      action: set
      int: 5

  mystery_award_hold_bonus_x:
    bonus_x_held:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 6

  mystery_award_super_spinner:
    super_spinner:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 7

  mystery_award_super_jets:
    super_jets:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 8

  mystery_award_playfield_x:
    playfield_multiplier:
      action: add
      int: 1
    mystery_awarded_index:
      action: set
      int: 9

  mystery_award_ambush:
    ambush:
      action: add
      int: 1
    mystery_awarded_index:
      action: set
      int: 10

  mystery_award_extra_ball_lit:
    extra_balls_lit:
      action: add
      int: 1
    extra_ball_mball_awarded:
      action: set
      int: 1
    mystery_awarded_index:
      action: set
      int: 15

  mystery_award_add_a_ball:
    mystery_awarded_index:
      action: set
      int: 14