#config_version=6

mode:
  start_events: start_col_difficulty_select
  stop_events:
    - villain_selection_complete
    - ball_ended
  priority: 310
  code: mpf.modes.carousel.code.carousel.Carousel


mode_settings:
  selectable_items:
    - col_die_hard
    - col_die_harder
  next_item_events:
    - s_right_flipper_active
  previous_item_events:
    - s_left_flipper_active
  select_item_events:
    - s_fire_active
    - s_actionbtn_active

show_player:
  mode_col_difficulty_select_started:
    flash_color:
      key: selected_villain_flash
      priority: 120
      loops: -1
      speed: 6
      show_tokens:
        lights: l44, l1000, l1001
        color: 0044ff

  set_difficulty_die_hard:
    selected_villain_flash:
      action: stop

  set_difficulty_die_harder:
    selected_villain_flash:
      action: stop
      
slide_player:
  mode_col_difficulty_select_started:
    col_difficulty_select:
      action: play
      expire: 0s
  play_col_intro:
    col_intro:
      action: play
      expire: 3s


event_player:
  carousel_item_selected{carousel=="col_difficulty_select" and item=="col_die_hard"}:
    - set_difficulty_die_hard
    - play_col_intro
    - villain_intro_finished|3s
  carousel_item_selected{carousel=="col_difficulty_select" and item=="col_die_harder"}:
    - set_difficulty_die_harder
    - play_col_intro
    - villain_intro_finished|3s
  villain_intro_finished:
    - release_villain_select_vuk
    - start_colonel_stuart
    - villain_selection_complete|100ms


variable_player:
  set_difficulty_die_hard:
    selected_diehard_mode:
      string: die_hard
      action: set


  set_difficulty_die_harder:
    selected_diehard_mode:
      string: die_harder
      action: set