#config_version=6

mode:
  start_events: start_katya_difficulty_select
  stop_events: villain_selection_complete, ball_ended
  priority: 310
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items: Die_Hard, Die_Harder
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active
  select_item_events: s_fire_active, s_actionbtn_active

slide_player:
  mode_katya_difficulty_select_started:
    katya_difficulty_select:
      action: play
      expire: 0s

  play_katya_intro:
    villain_katya_intro:
      action: play
      expire: 3s

event_player:
  carousel_item_selected{carousel=="katya_difficulty_select" and item=="Die_Hard"}:
    - set_difficulty_die_hard
    - play_katya_intro
    - villain_intro_finished|3s

  carousel_item_selected{carousel=="katya_difficulty_select" and item=="Die_Harder"}:
    - set_difficulty_die_harder
    - play_katya_intro
    - villain_intro_finished|3s

  villain_intro_finished:
    - release_villain_select_vuk
    - start_katya
    - villain_selection_complete|100ms

variable_player:
  set_difficulty_die_hard:
    selected_diehard_mode:
      string: die_hard
      action: set

  set_difficulty_die_harder:
    selected_diehard_mode:
      string: die_harder
      action: set