#config_version=6

mode:
  start_events: start_central_park_multiball{current_player.central_park_played==0}
  stop_events:
    - ball_ended
    - multiball_central_park_ended
  priority: 120

event_player:
  mode_qualify_central_park_stopped:
    - wire_ramp_exit_open
    - nakatomi_entrance_lock_close

  mode_central_park_multiball_started:
    - wire_ramp_exit_open
    - show_widget_park_jackpot_unlit

  slide_base_active:
    - wire_ramp_exit_open

  left_orbit_hit:
    - wire_ramp_exit_closed

  right_orbit_hit:
    - wire_ramp_exit_closed

  s_mid_orbit_active:
    - wire_ramp_exit_closed

  s_air_duct_active:
    - wire_ramp_exit_closed

  cp_jackpot_1_off_hit{current_player.park_super_jackpot_available == 0 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_1

  cp_jackpot_2_off_hit{current_player.park_super_jackpot_available == 0 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_2

  cp_jackpot_3_off_hit{current_player.park_super_jackpot_available == 0 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_3

  slide_jackpot_removed{current_player.shot_cp_jackpot_1 == 1 and current_player.shot_cp_jackpot_2 == 1 and current_player.shot_cp_jackpot_3 == 1}:
    - enable_park_super_jackpot
    - cp_bullets_advance_super_red|100ms

  cp_jackpot_1_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_super_advance == 2}:
    - score_park_super_jackpot
    - score_park_super_jackpot_hit
    - score_park_super_jackpot_1
    - check_restart_cp_jackpots

  cp_jackpot_2_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_super_advance == 2}:
    - score_park_super_jackpot
    - score_park_super_jackpot_hit
    - score_park_super_jackpot_2
    - check_restart_cp_jackpots

  cp_jackpot_3_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_super_advance == 2}:
    - score_park_super_jackpot
    - score_park_super_jackpot_hit
    - score_park_super_jackpot_3
    - check_restart_cp_jackpots

  check_restart_cp_jackpots{current_player.cp_super_jackpots_collected >= 3}:
    - restart_cp_jackpots

  restart_cp_jackpots:
    - remove_cp_super_jackpot_lit|100ms

  player_shot_cp_bullets_advance{value==0}:
    - show_widget_park_jackpot_unlit
  player_shot_cp_bullets_advance{value!=0}:
    - remove_widget_park_jackpot_unlit
  player_shot_cp_bullets_advance{value==1}:
    - show_widget_park_jackpot_lit
  player_shot_cp_bullets_advance{value!=1}:
    - remove_widget_park_jackpot_lit

multiballs:
  central_park:
    start_events: mode_central_park_multiball_started
    ball_count: 3
    ball_count_type: total
    shoot_again: 30s



light_player:
  mode_central_park_multiball_started:
    GI:
      color: ffb700
    SPOTS:
      color: 505050
    SPOTS_BUMPER:
      color: 969650

show_player: 
  score_park_jackpot: 
    park_jackpot: 
      key: park_mb_jackpot
      loops: 0
      speed: 2
  score_park_super_jackpot: 
    park_super_jackpot: 
      key: park_super_mb_jackpot
      loops: 0
      speed: 1

shots:
  cp_bullets_advance:
    profile: profile_cp_bullets_advance
    show_tokens:
      lights: l20,l22,l23,l24
    control_events:
      - events: score_park_jackpot
        state: 0
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 1
      - events: score_park_super_jackpot_hit
        state: 2
      - events: restart_cp_jackpots
        state: 0
      - events: cp_bullets_advance_super_red
        state: 2

  cp_single_bullet_advance:
    switch: s_upper_pf_entrance
    profile: profile_cp_single_bullet_advance
    enable_events:
      - mode_central_park_multiball_started
      - restart_cp_jackpots
    disable_events: enable_park_super_jackpot
    show_tokens:
      lights: l21
      color: 00ff00
    control_events:
      - events: restart_cp_jackpots
        state: 0
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 1
      - events: score_park_jackpot
        state: 0

  cp_single_bullet_super_advance:
    switch: s_upper_pf_entrance
    profile: profile_cp_single_bullet_advance
    enable_events: enable_park_super_jackpot
    disable_events: restart_cp_jackpots
    show_tokens:
      lights: l21
      color: ff0000
    control_events:
      - events: enable_park_super_jackpot
        state: 0
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 2
      - events: score_park_super_jackpot
        state: 0
      - events: restart_cp_jackpots
        state: 0


  cp_jackpot_1:
    switch: s_TrPF1
    profile: profile_cp_jackpot
    show_tokens:
      lights: l76
    control_events:
      - events: mode_central_park_multiball_started
        state: 0
      - events: restart_cp_jackpots
        state: 0
      - events: advance_cp_jackpot_1
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_1
        state: 3

  cp_jackpot_2:
    switch: s_TrPF2
    profile: profile_cp_jackpot
    show_tokens:
      lights: l77
    control_events:
      - events: mode_central_park_multiball_started
        state: 0
      - events: restart_cp_jackpots
        state: 0
      - events: advance_cp_jackpot_2
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_2
        state: 3

  cp_jackpot_3:
    switch: s_TrPF3
    profile: profile_cp_jackpot
    show_tokens:
      lights: l78
    control_events:
      - events: mode_central_park_multiball_started
        state: 0
      - events: restart_cp_jackpots
        state: 0
      - events: advance_cp_jackpot_3
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_3
        state: 3


slide_player:
  score_park_jackpot:
    jackpot:
      action: play
      expire: 0s

  score_park_super_jackpot:
    central_park_super_jackpot:
      action: play
      expire: 0s


widget_player:
  enable_park_super_jackpot:
    super_jackpot_lit:
      action: play
      slide: base
      key: cp_super_jackpot_lit
      expire: 0s
  remove_cp_super_jackpot_lit:
    super_jackpot_lit:
        action: remove
        slide: base
        key: cp_super_jackpot_lit
  show_widget_park_jackpot_unlit:
    park_jackpot_unlit:
      action: play
      slide: base
      key: widget_park_jackpot_unlit
      expire: 0s
  remove_widget_park_jackpot_unlit:
    park_jackpot_unlit:
      action: remove
      slide: base
      key: widget_park_jackpot_unlit
  show_widget_park_jackpot_lit:
    park_jackpot_lit:
      action: play
      slide: base
      key: widget_park_jackpot_lit
      expire: 0s
  remove_widget_park_jackpot_lit:
    park_jackpot_lit:
      action: remove
      slide: base
      key: widget_park_jackpot_lit

  score_park_super_jackpot:
    central_park_super_jackpot_widget:
      action: play
      expire: 0s


variable_player:
  mode_central_park_multiball_started:
    park_super_jackpot_available:
      action: set
      int: 0
    cp_super_jackpots_collected:
      action: set
      int: 0

  multiball_central_park_started:
    central_park_played:
      action: set
      int: 1

  enable_park_super_jackpot:
    park_super_jackpot_available:
      action: set
      int: 1
    cp_super_jackpots_collected:
      action: set
      int: 0

  score_park_super_jackpot_hit:
    cp_super_jackpots_collected:
      action: add
      int: 1
    score_park_super_jackpot_hit:
      action: set
      int: 1

  restart_cp_jackpots:
    park_super_jackpot_available:
      action: set
      int: 0
    cp_super_jackpots_collected:
      action: set
      int: 0

  score_park_jackpot:
    score:
      action: add
      int: 2000000
    last_jackpot_value:
      action: set
      int: 2000000

  score_park_super_jackpot_1:
    score:
      action: add
      int: 10000000

    last_jackpot_value:
      action: set
      int: 10000000

  score_park_super_jackpot_2:
    score:
      action: add
      int: 15000000

    last_jackpot_value:
      action: set
      int: 15000000

  score_park_super_jackpot_3:
    score:
      action: add
      int: 20000000

    last_jackpot_value:
      action: set
      int: 20000000

  