#config_version=6

mode:
  start_events: start_central_park_multiball
  stop_events: ball_ended,multiball_central_park_ended
  priority: 120

event_player:
  mode_qualify_central_park_stopped:
    - wire_ramp_exit_open
  player_shot_cp_bullets_advance:
    - wire_ramp_exit_closed
  player_shot_single_bullet_advance:
    - wire_ramp_exit_closed
  slide_base_active:
    - wire_ramp_exit_open

  cp_jackpot_1_off_hit{current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_1
  cp_jackpot_2_off_hit{current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_2
  cp_jackpot_3_off_hit{current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_jackpot
    - advance_cp_jackpot_3
  slide_jackpot_removed{current_player.shot_cp_jackpot_1 == 1 and current_player.shot_cp_jackpot_2 == 1 and current_player.shot_cp_jackpot_3 == 1}:
    - enable_park_super_jackpot


  cp_jackpot_1_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_super_jackpot
    - score_park_super_jackpot_1
  cp_jackpot_2_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_super_jackpot
    - score_park_super_jackpot_2
  cp_jackpot_3_super_hit{current_player.park_super_jackpot_available == 1 and current_player.shot_cp_single_bullet_advance == 1}:
    - score_park_super_jackpot
    - score_park_super_jackpot_3
  slide_super_jackpot_removed{current_player.shot_cp_jackpot_1 == 1 and current_player.shot_cp_jackpot_2 == 1 and current_player.shot_cp_jackpot_3 == 1}:
    - enable_super_jackpot_complete

multiballs: 
  central_park:
    start_events: mode_central_park_multiball_started
    ball_count: 3
    ball_count_type: total
    shoot_again: 30s

light_player: 
  mode_central_park_multiball_started: 
    GI: 
      color: ffb700
    SPOTS:
      color: 505050
    SPOTS_BUMPER:
      color: 969650

shots:
  cp_bullets_advance:
    profile: profile_cp_bullets_advance
    show_tokens: 
      lights: l20,l22,l23,l24
    control_events: 
      - events: score_park_jackpot
        state: 0
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 1
      - events: enable_park_super_jackpot,score_park_super_jackpot
        state: 2

   
  cp_single_bullet_advance:
    switch: s_upper_pf_entrance
    profile: profile_cp_single_bullet_advance
    disable_events: enable_park_super_jackpot
    show_tokens: 
      lights: l21
      color: 00ff00
    control_events: 
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 1
      - events: score_park_jackpot
        state: 0
  
  cp_single_bullet_super_advance:
    switch: s_upper_pf_entrance
    profile: profile_cp_single_bullet_advance
    enable_events: enable_park_super_jackpot
    show_tokens: 
      lights: l21
      color: ff0000
    control_events: 
      - events: left_orbit_hit,right_orbit_hit,s_mid_orbit_active,s_air_duct_active
        state: 2
      - events: score_park_super_jackpot, enable_park_super_jackpot
        state: 0


  cp_jackpot_1:
    switch: s_TrPF1
    profile: profile_cp_jackpot
    show_tokens: 
      lights: l76
    control_events: 
      - events: mode_central_park_multiball_started
        state: 0
      - events: advance_cp_jackpot_1
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_1
        state: 3

  cp_jackpot_2:
    switch: s_TrPF2
    profile: profile_cp_jackpot
    show_tokens: 
      lights: l77
    control_events:
      - events: mode_central_park_multiball_started
        state: 0
      - events: advance_cp_jackpot_2
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_2
        state: 3
 

  cp_jackpot_3:
    switch: s_TrPF3
    profile: profile_cp_jackpot
    show_tokens: 
      lights: l78
    control_events: 
      - events: mode_central_park_multiball_started
        state: 0
      - events: advance_cp_jackpot_3
        state: 1
      - events: enable_park_super_jackpot
        state: 2
      - events: score_park_super_jackpot_3
        state: 3



slide_player: 
 score_park_jackpot: 
    jackpot:
      action: play
      expire: 0s
 score_park_super_jackpot:
     super_jackpot:
      action: play
      expire: 0s

variable_player:
  multiball_central_park_started:
    central_park_played:
      action: set
      int: 1

  #Normal Jackpots
  score_park_jackpot:
    score: 
      action: add
      int: 2000000
    last_jackpot_value: 
      action: set
      int: 2000000
  
  #Super Jackpots
  score_park_super_jackpot: 
    score: 
      action: add
      int: 20000000
  
  enable_park_super_jackpot:
    park_super_jackpot_available:
      action: set
      int: 1 
