#config_version=6

ball_devices:

  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
  
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    player_controlled_eject_event: s_fire_active

  kickervault1_eject:
    ball_switches: s_kickervault1
    eject_coil: c_kickervault1_eject

  rightkicker:
    ball_switches: s_rightkicker
    eject_coil:   c_rightkicker_eject
    eject_timeouts: 1s

  UrampUp001:
    ball_switches: s_UrampUp001
    eject_coil: c_UrampUp001_eject
    eject_timeouts: 1s

  rightvuk:
    ball_switches: s_rightvuk
    eject_coil: c_rightvuk_eject
    eject_timeouts: 1s

  towervuk:
    ball_switches: s_towervuk
    eject_coil: c_towervuk_eject
    eject_timeouts: 1s
    
  airplane:
    ball_switches: s_captiveball
    eject_coil: c_captivetarget
    eject_timeouts: 1s