#config_version=6

switches:

 # trough switches
  s_trough1:
    number: d-29
    type: 'NC'
  s_trough2:
    number: d-24
  s_trough3:
    number: d-25
  s_trough4:
    number: d-26
  s_trough5:
    number: d-27
  s_trough6:
    number: d-28
  s_trough_jam:
    number: d-30
    type: 'NC'

 # Plungers
  s_plunger_lane:
    number: d-31
  s_kickervault1:
    number: d-2

 # Coin Door and cab Switches
  s_start:
    number: j-10
    tags: start
  s_door: 
    number: j-12
    type: 'NC'
  s_escape:
    number: j-0
  s_minus:
    number: j-1
  s_plus:
    number: j-2
  s_enter:
    number: j-3
  s_right_coin:
    number: j-4
  s_left_coin:
    number: j-5
  s_door_tilt:
    number: j-6
  s_tilt_bob:
    number: j-18
    tags: tilt_warning
  s_fire:
    number: j-11

 # Flippers
  s_right_flipper_eos:
    number: d-21
  s_left_flipper_eos:
    number: d-20
  s_left_flipper:
    number: j-9
    tags: left_flipper_top_flipper
  s_right_flipper:
    number: j-16
    tags: right_flipper
  s_top_flipper_eos:
    number: d-6

 # Magnets
  s_trmagl:
    number: j-17
    tags: left_magnet
  s_trmagr:
    number: j-8
    tags: right_magnet

 # three drop targets
  s_drop_target_1:
    number: e-2
    type: 'NC'
  s_drop_target_2:
    number: e-3
    type: 'NC'
  s_drop_target_3:
    number: e-4
    type: 'NC'

 # Nakatomi Lock Drop Target
  s_push_drop_target_4:
    number: e-6
 # Safe Lock Drop Target
  s_push_drop_target_5:
    number: d-3


 # Slings
  s_left_sling:
    number: d-18
    tags: left_slingshot
  s_right_sling:
    number: d-19
    tags: right_slingshot

# Lane Switches
  s_swrightoutlane:
    number: d-22
  s_swrightinlane:
    number: d-23
  s_swleftoutlane:
    number: d-17
  s_swleftinlane:
    number: d-16
  s_swrightorb1:
    number: e-14
  s_swleftorb1:
    number: d-7
  s_swrightorb2:
    number: f-4
  s_swleftorb2:
    number: f-0
  s_swmidorb:
    number: e-15

 # Top Targets
  s_target002:
    number: f-1
  s_target003:
    number: f-2
  s_target004:
    number: f-3

 # Holly Switches
  s_targeth:
    number: d-0
  s_targeto:
    number: d-1
  s_targetl:
    number: d-4
  s_targetl2:
    number: e-0
  s_targety:
    number: e-10

 # Pop Bumpers
  s_popbumper_left:
    number: e-5
    tags: left_pop_bumper
  s_popbumper_right:
    number: e-7
    tags: right_pop_bumper

 # spinners
  s_spinnerleft:
    number: d-5
  s_spinnerright:
    number: e-13


 # airplane
  s_captiveball:
    number: e-12

# air_ducts
  s_AirDuctEnter001: #And AirDuct002
    number: f-8
    type: 'NC'

 #vuks
  s_towervuk:
    number: e-1
    type: 'NC'
  s_rightkicker:
    number: e-9
    type: 'NC'
  s_UrampUp001:
    number: e-8
    type: 'NC'
  s_rightvuk:
    number: e-11
    type: 'NC'

# Top Playfield 
  s_swDivParkp:
    number: f-9
  s_TrPF1:
    number: f-6
    type: 'NC'
  s_TrPF2:
    number: f-7
    type: 'NC'
  s_TrPF3:
    number: f-5
    type: 'NC'