#config_version=6

switches:
 # trough switches
  s_trough1:
    number: d-0
    type: 'NC'
  s_trough2:
    number: d-1
  s_trough3:
    number: d-2
  s_trough4:
    number: d-3
  s_trough5:
    number: d-4
  s_trough6:
    number: d-5
  s_trough_jam:
    number: d-6
    type: NC


 # Plunger
  swPlunger:
    number: d-7


 # Slings
  s_left_sling:
    number: d-8
    tags: left_slingshot
  s_right_sling:
    number: d-9
    tags: right_slingshot

 # In and Outlanes
  s_left_outlane:
    number: d-10
  s_left_inlane:
    number: d-13
  s_right_inlane:
    number: d-17
  s_right_outlane:
    number: d-16

 # Coin Door and cab Switches
  s_start:
    number: j-10
    tags: start
  s_door:
    number: j-12
  s_escape:
    number: j-0
  s_minus:
    number: j-1
  s_plus:
    number: j-2
  s_enter:
    number: j-3
  s_right_coin:
    number: j-4
  s_left_coin:
    number: j-5
  s_door_tilt:
    number: j-6
  s_tilt_bob:
    number: j-18
    tags: tilt_warning
  s_fire:
    number: j-11

 # Flippers and Magnets
  s_right_flipper_eos:
    number: d-11
  s_left_flipper_eos:
    number: d-12
  s_left_flipper:
    number: j-9
    tags: left_and_top_flipper
  s_right_flipper:
    number: j-16
    tags: right_flipper
  s_top_flipper_hold:
    number: e-2
  s_left_magna:
    number: j-8
    tags: left_magnet
  s_right_magna:
    number: j-17
    tags: right_magnet

 # Pop Bumpers
  s_popbumper_left:
    number: e-0
    tags: left_pop_bumper
  s_popbumper_right:
    number: e-1
    tags: right_pop_bumper

 # Top Targets
  s_target_3:
    number: e-3
  s_target_2:
    number: e-4

 # Holly Switches
  s_holly_h:
    number: d-14
  s_holly_o:
    number: d-15
  s_holly_l:
    number: e-9
  s_holly_l_1:
    number: e-10
  s_holly_y:
    number: e-11

 # Vuks  
  s_safe_vuk:
    number: e-5
    type: 'NC'
  s_nakatomi:
    number: e-7
    type: 'NC'
  s_bottom_right_vuk:
    number: e-8
    type: 'NC'
  s_tunel_vuk:
    number: e-12
    type: 'NC'
  s_highvuk:
    number: e-13
    type: 'NC'

 # drop targets  
  s_drop_target_3:
    number: f-0
    type: 'NC'
  s_drop_target_2:
    number: f-1
    type: 'NC'
  s_drop_target_1:
    number: f-2
    type: 'NC'
