#config_version=6

switches:

 # trough switches
  s_trough1:
    number: d-8
    type: 'NC'
  s_trough2:
    number: d-9
  s_trough3:
    number: d-10
  s_trough4:
    number: d-11
  s_trough5:
    number: d-12
  s_trough6:
    number: d-13
  s_trough_jam:
    number: d-14
    type: 'NC'

 # Plunger
  s_plunger_lane:
    number: d-15

 # Coin Door and cab Switches
  s_start:
    number: j-10
    tags: start
  s_door: 
    number: j-12
    type: 'NC'
  s_escape:
    number: j-0
  s_minus:
    number: j-1
  s_plus:
    number: j-2
  s_enter:
    number: j-3
  s_right_coin:
    number: j-4
  s_left_coin:
    number: j-5
  s_door_tilt:
    number: j-6
  s_tilt_bob:
    number: j-18
    tags: tilt_warning
  s_fire:
    number: j-11

 # Flippers and Magnets
  s_right_flipper_eos:
    number: d-5
  s_left_flipper_eos:
    number: d-4
  s_left_flipper:
    number: j-9
    tags: left_flipper_top_flipper
  s_right_flipper:
    number: j-16
    tags: right_flipper
  s_top_flipper_eos:
    number: e-8
  s_left_magna:
    number: j-17
    tags: left_magnet
  s_right_magna:
    number: j-8
    tags: right_magnet

 # Slings
  s_left_sling:
    number: d-2
    tags: left_slingshot
  s_right_sling:
    number: d-3
    tags: right_slingshot

 # Pop Bumpers
  s_popbumper_left:
    number: e-6
    tags: left_pop_bumper
  s_popbumper_right:
    number: e-2
    tags: right_pop_bumper

 # Holly Switches
  s_holly_h:
    number: e-1
  s_holly_o:
    number: e-4
  s_holly_l:
    number: e-0
  s_holly_l1:
    number: e-5
  s_holly_y:
    number: e-11


  #Vuks  
  s_safe_vuk:
    number: e-3
    type: 'NC'
  s_nakatomi:
    number: e-7
    type: 'NC'
  s_bottom_right_vuk:
    number: e-13
    type: 'NC'
  s_tunel_vuk:
    number: e-12
    type: 'NC'
  s_highvuk:
    number: e-10
    type: 'NC'

 # spinners
  s_left spinner:
    number: e-9
  s_right spinner:
    number: e-15

 # airplane
  s_airplane:
    number: e-14

 # orbits
  s_left_orbit:
    number: d-16
  s_right_orbit:
    number: d-19


 # Top Targets
  s_left_top_target:
    number: d-18
  s_middle_top_target:
    number: d-20
  s_right_top_target:
    number: d-17

 # drop targets
  s_drop_target_3:
    number: f-0
    type: 'NC'
  s_drop_target_2:
    number: f-1
    type: 'NC'
  s_drop_target_1:
    number: f-2
    type: 'NC'


# In and Outlanes
  s_bottom_right_outer_drain:
    number: d-7
  s_bottom_right_inner_drain:
    number: d-6
  s_bottom_left_outer_drain:
    number: d-1
  s_bottom_left_inner_drain:
    number: d-0

# air_ducts
  s_AirDuctEnter001: #And AirDuct002
    number:  f-3
    type: 'NC'