#config_version=6

mode:
  start_events: ball_started,multiball_nakatomi_ended,multiball_central_park_ended,multiball_airplane_ended,ambush_ended
  stop_events: ball_ended,multiball_nakatomi_started,multiball_central_park_started,multiball_airplane_started,ambush_started
  priority: 110

event_player:

  left_orbit_hit{current_player.shot_bullet_left_orbit == 0}:
    - bullet_new_unique_shot
    - bullet_lock_left_orbit

  right_orbit_hit{current_player.shot_bullet_right_orbit == 0}:
    - bullet_new_unique_shot
    - bullet_lock_right_orbit

  bullet_mid_orbit_hit{current_player.shot_bullet_mid_orbit == 0}:
    - bullet_new_unique_shot
    - bullet_lock_mid_orbit

  bullet_air_duct_hit{current_player.shot_bullet_air_duct == 0}:
    - bullet_new_unique_shot
    - bullet_lock_air_duct

  bullet_upper_pf_hit{current_player.shot_bullet_upper_pf == 0}:
    - bullet_new_unique_shot
    - bullet_lock_upper_pf

  timer_bullets_combo_complete:
    - reset_bullets

  mode_bullets_stopping:
    - reset_bullets

  player_bullet_combo_hits{value==5}:
    - bullets_combo_max
    - villain_start_lit
    - reset_bullets|100ms

  player_bullet_hits{value>=15}:
    - villain_start_lit

  villain_start_lit:
    - reset_bullets|100ms

  right_vuk_hit{current_player.bullet_hits >= 15}:
    - start_villain_select
    - reset_bullet_total
    - reset_bullets

  right_vuk_hit{current_player.bullet_hits < 15}:
    - villain_start_not_ready


shots:

  bullet_left_orbit:
    profile: profile_bullets
    start_enabled: true
    show_tokens:
      lights: l50
    control_events:
      - events: reset_bullets
        state: 0
      - events: bullet_lock_left_orbit
        state: 1

  bullet_upper_pf:
    switch: s_upper_pf_entrance
    profile: profile_bullets
    start_enabled: true
    show_tokens:
      lights: l51
    control_events:
      - events: reset_bullets
        state: 0
      - events: bullet_lock_upper_pf
        state: 1

  bullet_right_orbit:
    profile: profile_bullets
    start_enabled: true
    show_tokens:
      lights: l53
    control_events:
      - events: reset_bullets
        state: 0
      - events: bullet_lock_right_orbit
        state: 1

  bullet_mid_orbit:
    switch: s_mid_orbit
    profile: profile_bullets
    start_enabled: true
    show_tokens:
      lights: l54
    control_events:
      - events: reset_bullets
        state: 0
      - events: bullet_lock_mid_orbit
        state: 1

  bullet_air_duct:
    switch: s_air_duct
    profile: profile_bullets
    start_enabled: true
    show_tokens:
      lights: l55
    control_events:
      - events: reset_bullets
        state: 0
      - events: bullet_lock_air_duct
        state: 1


show_player:

  bullets_combo_max:
    flicker_color:
      key: key_bullets_combo_max
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: bullets
        color: 00ff00

  bullet_lock_left_orbit:
    flicker_color:
      key: key_bullet_lock_left_orbit
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: BLO
        color: ff0000

  bullet_lock_right_orbit:
    flicker_color:
      key: key_bullet_lock_right_orbit
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: BRO
        color: ff0000

  bullet_lock_mid_orbit:
    flicker_color:
      key: key_bullet_lock_mid_orbit
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: BMO
        color: ff0000

  bullet_lock_air_duct:
    flicker_color:
      key: key_bullet_lock_air_duct
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: BAD
        color: ff0000

  bullet_lock_upper_pf:
    flicker_color:
      key: key_bullet_lock_upper_pf
      priority: 1
      loops: 2
      speed: 4
      show_tokens:
        lights: BUP
        color: ff0000

  villain_start_lit:
    flash_color:
      key: key_villain_start_lit
      priority: 10
      loops: -1
      speed: 4
      show_tokens:
        lights: l10
        color: F5D327

  start_villain_select:
    key_villain_start_lit:
      action: stop


light_player:

  start_villain_select:
    l10:
      color: F5D327

  reset_bullet_total:
    l10:
      color: off


timers:

  bullets_combo:
    start_value: 65
    end_value: 0
    direction: down
    control_events:
      - event: bullet_new_unique_shot
        action: restart
      - event: villain_start_lit
        action: stop
    restart_on_complete: false
    start_running: false
    tick_interval: 100ms


variable_player:

  bullet_new_unique_shot:

    bullet_hits:
      action: add
      int: 1 + current_player.bullet_combo_hits

    eob_bonus_bullet:
      action: add
      int: 35000 * (1 + current_player.bullet_combo_hits)

    bullet_combo_hits:
      action: add
      int: 1

  reset_bullets:

    bullet_combo_hits:
      action: set
      int: 0

  reset_bullet_total:

    bullet_hits:
      action: set
      int: 0

    bullet_combo_hits:
      action: set
      int: 0