#config_version=6

mode:
  start_events: ball_started{current_player.airplane_mb_played==0}multiball_nakatomi_ended,multiball_central_park_ended,ambush_ended
  stop_events: ball_ended,multiball_nakatomi_started,multiball_central_park_started,ambush_started
  priority: 150


ball_saves:
  airplane_save:
    active_time: 8s           
    hurry_up_time: 4s                
    enable_events: airplane_ball_3_locked_complete
    disable_events: start_airplane_multiball
    auto_launch: true
    balls_to_save: -1

event_player:
  mode_qualify_airplane_started:
    - airplane_reset_locks
    - airplane_enable_lock_counter
  counter_airplane_light_lock_hit{hits==5}:
    - lock_lit
    - airplane_disable_lock_counter
  s_UrampUp001_active{current_player.airplane_lock_lit==1 and current_player.airplane_virtual_locks==0}:
    - airplane_ball_1_locked_complete
  s_UrampUp001_active{current_player.airplane_lock_lit==1 and current_player.airplane_virtual_locks==1}:
    - airplane_ball_2_locked_complete
  s_UrampUp001_active{current_player.airplane_lock_lit==1 and current_player.airplane_virtual_locks==2}:
    - airplane_ball_3_locked_complete
  airplane_ball_1_locked_complete:
    - airplane_ball_1_locked
    - airplane_reset_locks
    - airplane_enable_lock_counter
  airplane_ball_2_locked_complete:
    - airplane_ball_2_locked
    - airplane_reset_locks
    - airplane_enable_lock_counter
  airplane_ball_3_locked_complete:
    - airplane_ball_3_locked
    - airplane_disable_lock_counter
  slide_airplane_mb_removed:
   - start_airplane_multiball


counters:
  airplane_light_lock:
    count_events: s_captiveball_active
    count_complete_value: 5
    enable_events: airplane_enable_lock_counter
    disable_events:
      - airplane_disable_lock_counter
      - airplane_multiball_start
    reset_events: airplane_reset_locks
    persist_state: false


shots:
  airplane_save:
    profile: shoot_again
    show_tokens: 
      color: ff0000
    enable_events: airplane_ball_3_locked_complete
    disable_events: start_airplane_multiball
    control_events: 
      - events: qualify_airplane_on_complete
        state: 1

  airplane_lock_1:
    switch: s_captiveball
    profile: profile_airplane_light_off
    show_tokens:
      lights: l62
    control_events:
      - events: lock_lit
        state: 0
      - events: airplane_reset_locks
        state: 1
      - events: airplane_ball_3_locked_complete
        state: 2

  airplane_lock:
    switch: s_captiveball
    profile: profile_airplane_lock_lit
    show_tokens:
      lights: l61
    control_events:
      - events: lock_lit
        state: 0
      - events: airplane_reset_locks
        state: 1
      - events: airplane_ball_3_locked_complete
        state: 2

  airplane_lock_complete:
    switch: s_UrampUp001

slide_player:
  airplane_ball_1_locked_complete:
    airplane_ball_1:
      action: play
      expire: 0s
  airplane_ball_2_locked_complete:
    airplane_ball_2:
      action: play
      expire: 0s
  airplane_ball_3_locked_complete:
    airplane_mb:
      action: play
      expire: 0s


variable_player:
  mode_started:
    airplane_lock_lit:
      int: 0
      action: set
    airplane_virtual_locks:
      int: 0
      action: set
  counter_airplane_light_lock_hit{hits==5}:
    airplane_lock_lit:
      int: 1
      action: set
  airplane_ball_1_locked_complete:
    airplane_virtual_locks:
      int: 1
      action: add
    airplane_lock_lit:
      int: 0
      action: set
  airplane_ball_2_locked_complete:
    airplane_virtual_locks:
      int: 1
      action: add
    airplane_lock_lit:
      int: 0
      action: set
  airplane_ball_3_locked_complete:
    airplane_virtual_locks:
      int: 1
      action: add
    airplane_lock_lit:
      int: 0
      action: set

