#config_version=6

mode:
  start_events: ball_started{current_player.airplane_multiball_played==0},multiball_nakatomi_ended,multiball_central_park_ended
  stop_events: ball_ended,multiball_central_park_started,multiball_nakatomi_started
  priority: 150



