#config_version=6

mode:
  start_events: multiball_nakatomi_started
  stop_events: ball_ended, multiball_nakatomi_ended
  priority: 120

light_player: 
  mode_nakatomi_multiball_started: 
    GI: 
      color: ffb700
    SPOTS:
      color: 505050
    SPOTS_BUMPER:
      color: 969650

event_player:
  nakatomi_jackpots_on_hit:
    - jackpot_2mil
  nakatomi_jackpots_off_complete:
    - nakatomi_enable_super_jackpot
  nakatomi_super_jackpot_hit:
    - jackpot_20mil
    - nakatomi_disable_super_jackpot
    - nakatomi_super_jackpot_collected

shot_groups: 
  nakatomi_jackpots:
    shots: bullet_left_orbit_nakatomi,bullet_upper_pf_nakatomi,bullet_right_orbit_nakatomi,bullet_mid_orbit_nakatomi,bullet_air_duct_nakatomi
    restart_events: nakatomi_disable_super_jackpot

shots: 
  bullet_left_orbit_nakatomi:
    profile: profile_nakatomi
    start_enabled: True
    show_tokens: 
      lights: l20
    hit_events: left_orbit_hit
  bullet_upper_pf_nakatomi:
    switch: s_upper_pf_entrance
    profile: profile_nakatomi
    start_enabled: True
    show_tokens: 
      lights: l21
  bullet_right_orbit_nakatomi: 
    profile: profile_nakatomi
    start_enabled: True
    show_tokens: 
      lights: l22
    hit_events: right_orbit_hit
  bullet_mid_orbit_nakatomi:
    switch: s_mid_orbit
    profile: profile_nakatomi
    start_enabled: True
    show_tokens: 
      lights: l23
  bullet_air_duct_nakatomi:
    switch: s_air_duct
    profile: profile_nakatomi
    start_enabled: True
    show_tokens: 
      lights: l24
  nakatomi_super_jackpot:
    profile: profile_off_then_flash
    show_tokens: 
      lights: l7
      color: 0000ff
    control_events: 
      - events: nakatomi_enable_super_jackpot
        state: 1
      - events: nakatomi_disable_super_jackpot
        state: 0

slide_player: 
  nakatomi_jackpots_on_hit: 
    jackpot:
      action: play
      expire: 0s
  nakatomi_super_jackpot_collected: 
    super_jackpot:
      action: play
      expire: 0s


variable_player: 
  slide_nakatomi_mb_removed: 
    played_naktomi_multiball: 
      action: set
      int: 1

  jackpot_2mil: 
    score: 
      action: add
      int: 2000000
    last_jackpot_value: 
      action: set
      int: 2000000

  jackpot_20mil: 
    score: 
      action: add
      int: 20000000
    last_jackpot_value: 
      action: set
      int: 20000000
    nakatomi_super_jackpot_collected: 
      action: set
      int: 1




