#config_version=6

mode:
  start_events: ball_ending{game.tilted == False}
  stop_events: bonus_finished
  priority: 9999
  use_wait_queue: true

combo_switches: 
  flipper_cancel_bonus:
    switches_1: s_left_flipper
    switches_2: s_right_flipper
    events_when_both: 
      - show_bonus_summary

event_player: 
  timer_eob_bonus_complete: 
    - show_bonus_summary
  timer_eob_bonus_summary_complete: 
    - bonus_finished
  mode_eob_bonus_started: 
    - stop_main_music1
    - stop_main_music2
    - stop_main_music3
    - stop_main_music4


show_player: 
  mode_eob_bonus_started: 
    eob_bonus: 
      key: key_eob_bonus
      loops: 0
  show_bonus_summary: 
    eob_bonus: 
      action: stop
      key: key_eob_bonus


slide_player: 
  show_bonus_summary: 
    eob_bonus_summary:
      action: play
      expire: 0s


sound_player: 
  stop_main_music1: 
    gameplay_music_beethoven: 
      key: main_snd_music
      action: stop
  stop_main_music2: 
    gameplay_music_assault: 
      key: main_snd_music
      action: stop
  stop_main_music3: 
    gameplay_music_finlandia: 
      key: main_snd_music
      action: stop
  stop_main_music4: 
    gameplay_music_battle: 
      key: main_snd_music
      action: stop


timers: 
  eob_bonus:
    start_value: 0
    end_value: 12
    direction: up
    control_events: 
      - event: show_bonus_summary
        action: stop
    restart_on_complete: False
    start_running: True
    tick_interval: 1000ms
  eob_bonus_summary:
    start_value: 0
    end_value: 3
    direction: up
    control_events: 
      - event: show_bonus_summary
        action: start
    restart_on_complete: False
    start_running: False
    tick_interval: 1000ms


