#config_version=6

mode:
  start_events: start_hans_diehard

  stop_events:
    - hans_diehard_won_complete
    - hans_diehard_failed_complete

  priority: 160

timers:
  hans_diehard_timer:
    start_value: 93
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false

    control_events:
      - event: mode_hans_diehard_started
        action: restart

      - event: hans_diehard_won_complete
        action: stop

      - event: hans_diehard_failed_complete
        action: stop

counters:
  hans_diehard_detonators:
    count_events:
      - hans_diehard_valid_h
      - hans_diehard_valid_o
      - hans_diehard_valid_l1
      - hans_diehard_valid_l2
      - hans_diehard_valid_y

    starting_count: 0
    count_complete_value: 8
    direction: up
    persist_state: false
    reset_on_complete: false

    events_when_complete:
      - hans_diehard_complete

shots:
  hans_diehard_h:
    switch: s_holly_h
    enable_events:
      - mode_hans_diehard_started
      - hans_diehard_h_ready
    disable_events:
      - hans_diehard_valid_h

  hans_diehard_o:
    switch: s_holly_o
    enable_events:
      - mode_hans_diehard_started
      - hans_diehard_o_ready
    disable_events:
      - hans_diehard_valid_o

  hans_diehard_l1:
    switch: s_holly_l
    enable_events:
      - mode_hans_diehard_started
      - hans_diehard_l1_ready
    disable_events:
      - hans_diehard_valid_l1

  hans_diehard_l2:
    switch: s_holly_l1
    enable_events:
      - mode_hans_diehard_started
      - hans_diehard_l2_ready
    disable_events:
      - hans_diehard_valid_l2

  hans_diehard_y:
    switch: s_holly_y
    enable_events:
      - mode_hans_diehard_started
      - hans_diehard_y_ready
    disable_events:
      - hans_diehard_valid_y

event_player:
  mode_hans_diehard_started:
    - villain_mode_started
    - hans_diehard_h_ready
    - hans_diehard_o_ready
    - hans_diehard_l1_ready
    - hans_diehard_l2_ready
    - hans_diehard_y_ready
    - hans_diehard_music_start
    - hans_diehard_show_timer
    - hans_diehard_message_start
    - nakatomi_entrance_lock_close
    - release_villain_select_vuk

  mode_hans_diehard_stopping:
    - villain_mode_stopped

  hans_diehard_h_hit:
    - hans_diehard_valid_h

  hans_diehard_o_hit:
    - hans_diehard_valid_o

  hans_diehard_l1_hit:
    - hans_diehard_valid_l1

  hans_diehard_l2_hit:
    - hans_diehard_valid_l2

  hans_diehard_y_hit:
    - hans_diehard_valid_y

  hans_diehard_valid_h:
    - hans_diehard_h_ready|3s
    - hans_diehard_update_display
    - hans_diehard_target_hit

  hans_diehard_valid_o:
    - hans_diehard_o_ready|3s
    - hans_diehard_update_display
    - hans_diehard_target_hit

  hans_diehard_valid_l1:
    - hans_diehard_l1_ready|3s
    - hans_diehard_update_display
    - hans_diehard_target_hit

  hans_diehard_valid_l2:
    - hans_diehard_l2_ready|3s
    - hans_diehard_update_display
    - hans_diehard_target_hit

  hans_diehard_valid_y:
    - hans_diehard_y_ready|3s
    - hans_diehard_update_display
    - hans_diehard_target_hit

  hans_diehard_complete:
    - hans_diehard_completed_slide|4s
    - hans_diehard_won_complete|8s

  timer_hans_diehard_timer_complete:
    - hans_lost_slide
    - hans_diehard_failed_complete|4s

  ball_drain:
    - hans_lost_slide
    - hans_diehard_failed_complete|4s

variable_player:
  mode_hans_diehard_started:
    villain_mode_running:
      int: 1
      action: set

    hans_diehard_progress:
      int: 0
      action: set

    hans_diehard_time:
      int: 93
      action: set

    hans_diehard_remaining:
      int: 8
      action: set

  timer_hans_diehard_timer_tick:
    hans_diehard_time:
      int: ticks
      action: set

  logicblock_hans_diehard_detonators_hit:
    hans_diehard_remaining:
      int: 8 - device.counters.hans_diehard_detonators.value
      action: set

  hans_diehard_target_hit{device.counters.hans_diehard_detonators.value<8}:
    score: 1000000

    hans_diehard_progress:
      int: 1
      action: add

  hans_diehard_won_complete:
    score: 3000000

    hans_complete:
      int: 1
      action: set

    hans_diehard_complete:
      int: 1
      action: set

  mode_hans_diehard_stopping:
    villain_mode_running:
      int: 0
      action: set

show_player:
  hans_diehard_target_hit:
    flash_color:
      key: hans_gi_red_hit_flash
      priority: 300
      loops: 3
      speed: 10

      show_tokens:
        lights: GI
        color: ff0000

  mode_hans_diehard_started:
    flash_color:
      key: hans_gruber_flash
      priority: 160
      loops: -1
      speed: 6

      show_tokens:
        lights: l43
        color: red

  hans_diehard_h_ready:
    hans_bullet_flash:
      key: hans_h_flash
      priority: 170
      loops: -1

      show_tokens:
        light: l30

  hans_diehard_o_ready:
    hans_bullet_flash:
      key: hans_o_flash
      priority: 170
      loops: -1

      show_tokens:
        light: l31

  hans_diehard_l1_ready:
    hans_bullet_flash:
      key: hans_l1_flash
      priority: 170
      loops: -1

      show_tokens:
        light: l32

  hans_diehard_l2_ready:
    hans_bullet_flash:
      key: hans_l2_flash
      priority: 170
      loops: -1

      show_tokens:
        light: l33

  hans_diehard_y_ready:
    hans_bullet_flash:
      key: hans_y_flash
      priority: 170
      loops: -1

      show_tokens:
        light: l34

  hans_diehard_valid_h:
    hans_h_flash:
      action: stop

  hans_diehard_valid_o:
    hans_o_flash:
      action: stop

  hans_diehard_valid_l1:
    hans_l1_flash:
      action: stop

  hans_diehard_valid_l2:
    hans_l2_flash:
      action: stop

  hans_diehard_valid_y:
    hans_y_flash:
      action: stop

  mode_hans_diehard_stopping:
    hans_gi_red_hit_flash:
      action: stop

    hans_gruber_flash:
      action: stop

    hans_h_flash:
      action: stop

    hans_o_flash:
      action: stop

    hans_l1_flash:
      action: stop

    hans_l2_flash:
      action: stop

    hans_y_flash:
      action: stop

light_player:
  mode_hans_diehard_started:
    GI:
      color: 00ff00

    SPOTS:
      color: 332200

slide_player:
  mode_hans_diehard_started:
    hans_diehard_background:
      action: play
      expire: 0s
      priority: 500

  mode_hans_diehard_stopping:
    hans_diehard_background:
      action: remove

  logicblock_hans_diehard_detonators_hit{count==1}:
    detonator_1:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==2}:
    detonator_2:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==3}:
    detonator_3:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==4}:
    detonator_4:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==5}:
    detonator_5:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==6}:
    detonator_6:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==7}:
    detonator_7:
      action: play
      expire: 4s
      priority: 600

  logicblock_hans_diehard_detonators_hit{count==8}:
    detonator_8:
      action: play
      expire: 4s
      priority: 600

  hans_diehard_completed_slide:
    detonators_completed:
      action: play
      expire: 4s
      priority: 10000

  hans_lost_slide:
    hans_lost:
      action: play
      expire: 4s
      priority: 10000

widget_player:
  mode_hans_diehard_started:
    hans_timer_widget:
      slide: hans_diehard_background
      action: play

    hans_progress_widget:
      slide: hans_diehard_background
      action: play

  mode_hans_diehard_stopping:
    hans_timer_widget:
      action: remove

    hans_progress_widget:
      action: remove

sound_player:
  hans_diehard_music_start:
    holly_meets_hans:
      action: play
      loops: -1
      volume: 0.7

  mode_hans_diehard_stopping:
    holly_meets_hans:
      action: stop